Repository Kkrap-team/Backend, pull requests merged in 2025-04, with the labels that each got.

#22 feat : Links 선택 삭제, 하나 삭제 기능 추가
  src/main/java/com/Kkrap/Controller/LinksController.java
  src/main/java/com/Kkrap/RequestDTO/LinksDeleteDTO.java
  src/main/java/com/Kkrap/RequestDTO/LinksDeleteRequest.java
  src/main/java/com/Kkrap/Service/LinksService.java
Labels: feat

#26 Swagger 기능 추가
  build.gradle
  src/main/java/com/Kkrap/Util/SwaggerConfig.java
Labels: feat, chore

#27 [refactor] 카카오 로그인 AuthController로 변경, 각 URL /v2 삭제
  src/main/java/com/Kkrap/Controller/AuthController.java
  src/main/java/com/Kkrap/Controller/FoldersController.java
  src/main/java/com/Kkrap/Controller/LinksController.java
  src/main/java/com/Kkrap/Controller/UsersController.java
  src/main/java/com/Kkrap/Entity/Folders.java
  src/main/java/com/Kkrap/Entity/Users.java
  src/main/java/com/Kkrap/Exception/ErrorCode.java
  src/main/java/com/Kkrap/Exception/FoldersNotFoundException.java
  src/main/java/com/Kkrap/Exception/GlobalExceptionHandler.java
  src/main/java/com/Kkrap/Exception/UsersNotFoundException.java
  src/main/java/com/Kkrap/Repository/UsersRepository.java
  src/main/java/com/Kkrap/RequestDTO/FoldersCreateRequest.java
  src/main/java/com/Kkrap/RequestDTO/FoldersDeleteRequest.java
  src/main/java/com/Kkrap/RequestDTO/UsersCreateRequest.java
  src/main/java/com/Kkrap/ResponseDto/ErrorResponse.java
  src/main/java/com/Kkrap/ResponseDto/FoldersDeleteResponse.java
  src/main/java/com/Kkrap/ResponseDto/FoldersLinksAllResponse.java
  src/main/java/com/Kkrap/ResponseDto/FoldersResponse.java
  src/main/java/com/Kkrap/ResponseDto/MessageResponse.java
  src/main/java/com/Kkrap/ResponseDto/UserProfileResponse.java
  src/main/java/com/Kkrap/ResponseDto/UsersProfileResponse.java
  src/main/java/com/Kkrap/Security/SecurityConfig.java
  src/main/java/com/Kkrap/Service/AuthService.java
  src/main/java/com/Kkrap/Service/FoldersService.java
  src/main/java/com/Kkrap/Service/UsersService.java
Labels: refactor

#29 refactor: token 값이 전달되지 않은 예외, token 값이 존재할 때에 발생하는 핸들링 메서드 분리, 테스트 검증
  src/main/java/com/Kkrap/Controller/AuthController.java
  src/main/java/com/Kkrap/Exception/ErrorCode.java
  src/main/java/com/Kkrap/Exception/GlobalExceptionHandler.java
  src/main/java/com/Kkrap/Exception/NotValidTokenException.java
  src/main/java/com/Kkrap/Service/AuthService.java
  src/test/java/com/Kkrap/Auth/AuthControllerTest.java
  src/test/java/com/Kkrap/Auth/AuthServiceTest.java
Labels: refactor

#31 chore : FoldersController, FoldersService 메서드 이름 변경, isPublic을 visible로 변경
  src/main/java/com/Kkrap/Controller/FoldersController.java
  src/main/java/com/Kkrap/Entity/Folders.java
  src/main/java/com/Kkrap/RequestDTO/FoldersCreateRequest.java
  src/main/java/com/Kkrap/ResponseDto/FoldersLinksAllResponse.java
  src/main/java/com/Kkrap/ResponseDto/FoldersResponse.java
  src/main/java/com/Kkrap/Service/AuthService.java
  src/main/java/com/Kkrap/Service/FoldersService.java
Labels: chore

#32 feat : dockerfile 작성
  Dockerfile
Labels: feat

#35 refactor : 예외 처리 코드, links 저장(EC2), ProfileImage 저장, DTO Schema
  src/main/java/com/Kkrap/Controller/LinksController.java
  src/main/java/com/Kkrap/Exception/DuplicateNickNameException.java
  src/main/java/com/Kkrap/Exception/ErrorCode.java
  src/main/java/com/Kkrap/Exception/FoldersNotFoundException.java
  src/main/java/com/Kkrap/Exception/GlobalExceptionHandler.java
  src/main/java/com/Kkrap/Exception/LinksNotFoundException.java
  src/main/java/com/Kkrap/Exception/NotValidTokenException.java
  src/main/java/com/Kkrap/Exception/SaveFileErrorException.java
  src/main/java/com/Kkrap/Exception/UsersNotFoundException.java
  src/main/java/com/Kkrap/RequestDTO/FoldersCreateRequest.java
  src/main/java/com/Kkrap/RequestDTO/FoldersDeleteRequest.java
  src/main/java/com/Kkrap/RequestDTO/KaKaoTokenRequest.java
  src/main/java/com/Kkrap/RequestDTO/LinksCreateRequest.java
  src/main/java/com/Kkrap/RequestDTO/LinksDeleteRequest.java
  src/main/java/com/Kkrap/ResponseDto/ErrorResponse.java
  src/main/java/com/Kkrap/ResponseDto/LinksCreateResponse.java
  src/main/java/com/Kkrap/ResponseDto/LinksResponse.java
  src/main/java/com/Kkrap/Security/SecurityConfig.java
  src/main/java/com/Kkrap/Service/AuthService.java
  src/main/java/com/Kkrap/Service/FoldersService.java
  src/main/java/com/Kkrap/Service/LinksService.java
  src/main/java/com/Kkrap/Service/UsersService.java
  src/main/java/com/Kkrap/Util/CustomJsonParser.java
  src/main/java/com/Kkrap/Util/FileStorageUtil.java
  src/main/java/com/Kkrap/Util/HTMLScriptExtractor.java
  src/main/java/com/Kkrap/Util/LinkMetadataExtractor.java
Labels: chore, refactor

#36 feat : 하나의 폴더 전체 링크 최신순 조회, 하나의 폴더 전체 링크 4개 최신순 조회(썸네일 전용), 모든 폴더 및 링크 조회 최신순 변경
  src/main/java/com/Kkrap/Controller/FoldersController.java
  src/main/java/com/Kkrap/Service/FoldersService.java
Labels: feat
